=== oscarmcc/Insti/reenctregaU5LLMM/ej5-OscarXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Óscar Martín-Castaño Carrillo-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="productos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="producto" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="producto">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="descripcion" type="xs:string"/>
        <xs:element name="cantidad" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="codigo" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{5}"></xs:pattern>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== oscarmcc/Insti/reenctregaU5LLMM/ej5-Oscar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Óscar Martín-Castaño Carrillo-->
<productos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./ej5-OscarXSD.xsd">
   <producto codigo="12345">
      <descripcion>Tipo A</descripcion>
      <cantidad>3</cantidad>
   </producto>
   <producto codigo="98765">
      <descripcion>Tipo B</descripcion>
      <cantidad>5</cantidad>
   </producto>
   <producto codigo="54321">
      <descripcion>Tipo C</descripcion>
      <cantidad>2</cantidad>
   </producto>
</productos>
